### ISSUE TITLE
Some evidences can have empty title and text file

### ISSUE THREAD

**Issue by elreplicante** [huridocs/preserve#108]
Preserving an URL that performs several redirects can lead to evidence with the title as an empty string and a content txt file with 0 bytes.

An example URL is `http://youtu.be`.

**Comment by daneryl** [comment]
> Let's try to follow the redirects

Tested this and puppeteer is actually following the redirects and assigning the proper title

> Why is title empty, if all websites have a title?

There are some sites that just have empty titles, one i have seen on the evidences: chrome://extensions, should we assign the url as the title when it is empty ?

**Comment by elreplicante** [comment]
> There are some sites that just have empty titles, one i have seen on the evidences: chrome://extensions, should we assign the url as the title when it is empty ?

That seems a good roundtrip to me in this case.
