### ISSUE TITLE
Hide the install section temporarily

### ISSUE THREAD

**Issue by nwyu** [huridocs/preserve#350]
The Preserve Extension has not yet been published on the Chrome or Firefox stores, thus this install section does not currently serve any purpose.

![extension store link](https://user-images.githubusercontent.com/56067374/187959486-54354dbe-8af5-439a-98cb-808465700de5.png)

**Comment by Zasa-san** [comment]
In the extension screen we have this message at the bottom `Some information about the token`
![Image](https://user-images.githubusercontent.com/71732018/190422005-2ba43c95-2f33-42c0-a15f-fb50d84eeda7.png)

Should we update this with some text or leave it? Or just remove it?

@nwyu

**Comment by nwyu** [comment]
@Zasa-san We need to hide only the part above the line. Please leave everything below the Configuration "Extension Token" section. 

As an aside, let's keep the heading "Preserve Extension", but could you add the logo there (in addition to the sidebar in #351)? Thanks!

**Comment by nwyu** [comment]
@Zasa-san Let's remove the 'Some information about the token' text.
